### ISSUE TITLE
Program stalls on Apply Preset, loads infinitely

### ISSUE THREAD

**Issue by DILWeed6499** [Stekeblad/Stekeblads-Video-Uploader#10]
I've tried many different presets, videos, etc and for whatever reason for me anytime I try to apply a preset to upload a video it just sits loading like in this screencap, never showing videos in the large bottom area like it does in your tutorial videos. It's impossible to upload videos like this.
![image](https://user-images.githubusercontent.com/10789889/70867210-ffe83f00-1f40-11ea-8710-bf73c764a015.png)
I wish I could provide more info on why/what causes it but it's just not working for me at all.

**Comment by Stekeblad** [comment]
Hi DILWeed6499 and thank you for trying Stekeblads Video Uploader 

Do you mean the entire program freezes? Does the progress indicator at the top move and does any of the buttons work?

Would you like to share any of the presets you tried with?

In development I noticed that applying presets that use the metadata tag sometimes was realy slow. That depends on the video files and how the meta data is saved inside them and if that is the case I can not do anything. Sometimes the meta data can be found in the beginning of the file and can quickly be extracted, but it may also be located later in it or even at the end and for large files it can take several minutes to find the meta data.

Can you try using the metadata tool (found in the settings window) and see if it show anything for some of the files you tried?

**Comment by DILWeed6499** [comment]
The program doesn't freeze, but it doesn't progress past the loading bar (I've left it open for an hour trying to process the screencap there and it is still going.) The rest of the program still functions fine, though I can't cancel it trying to apply the preset in any way.
The main preset I've tried uses the metadata tag extensively, but I've also tried one with no metadata tag usage and it had the same issue. 
![image](https://user-images.githubusercontent.com/10789889/70868195-2495e400-1f4c-11ea-88bc-64ac2975e009.png)
The videos I'm trying to upload were made by combining a jpeg with a flac file using ffmpeg to make a single-frame video, so there could be some weirdness there. The program seems to load their tags fine though.
![image](https://user-images.githubusercontent.com/10789889/70868227-a0902c00-1f4c-11ea-9b44-1a776c967721.png)

**Comment by Stekeblad** [comment]
Thank you, I will look into this.

**Comment by Stekeblad** [comment]
Hi DILWeed6499,
I have not been able to figure out the reason behind the problem you are experiencing.

However I have added more code for catching errors and showing detailed error messages in version 1.3.2 that I just uploaded. Could you try with the latest version and see if you get any error messages?

Most errors is also automatically printed to the console so if you have some experience with the command prompt you could try launching the program from there by navigating to the directory you have the program in and running the following command:
`java -jar Stekeblads_Video_Uploader_v1_3_2.jar`
Then try applying the preset to your videos again and look in the console if it prints anything.

**Comment by DILWeed6499** [comment]
Just tried it again and it popped up an error window for each video with the following
`Sorry, something went wrong!
Here is the error details:
-----------------------------------------
null
-----------------------------------------
java.lang.NullPointerException
	at io.github.stekeblad.videouploader.youtube.VideoInformationBase.setButton1(VideoInformationBase.java:180)
	at io.github.stekeblad.videouploader.utils.state.VideoUploadState.set(VideoUploadState.java:114)
	at io.github.stekeblad.videouploader.utils.state.VideoUploadState.setLocked(VideoUploadState.java:57)
	at io.github.stekeblad.videouploader.main.mainWindowController.onPresetApplicationSuccess(mainWindowController.java:843)
	at io.github.stekeblad.videouploader.main.mainWindowController.lambda$null$6(mainWindowController.java:149)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by Stekeblad** [comment]
Hi DILWeed6499,
Thank you for the error details. I have not been able to recreate what you experience or see how the code could fail the way it does. However it tells me how it fails and I have tried fixing it. I am about to upload version 1.3.3 that hopefully fixes it.

You also pointed out that you got one error message per video and the update also contains a change that prevents identical error messages to appear multiple times very fast. The initial limit is 15 seconds before they can appear again but I may change the cooldown time later.

I am also a bit curious about what happens if you add the videos but do not select a preset before pressing apply preset, does it also give you an error message?
