### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by kast1450** [Stekeblad/Stekeblads-Video-Uploader#12]
"This app has not been verified yet by Google in order to use Google Sign In."

**Comment by Stekeblad** [comment]
This is a known issue and I am slowly working on checking the requirements for verification and settings up the prerequisites before I can submit for verification.

**Comment by Stekeblad** [comment]
This is the current status, I will update this comment over time I fix things.

**prerequisites**
Submission for verification can not be submitted at all 
- [x] Create a [website](https://stekeblad.se) for hosting important pages like the [Privacy Policy](https://stekeblad.se/Projects/Video-uploader/uploader-privacy)
- [x] Verify the site ownership with Google

**Requirements**
Review all YouTube's requirements for programs using their API
- [ ] Update to the latest version of the YouTube API
- [ ] Add support for the new Made For Kids-option
- [ ] Create an update checker. (With automatic updates?)
- [ ] A few small things that do not need their own point on this list.

**More things**
- [ ] Update links to point to the new website
- [ ] Review the privacy policy again after implementing the changes
- [ ] Update wiki for the new release
- [ ] Create and upload release

**Lastly**
- [ ] Submit for verification
- [ ] Pass the verification

**Comment by Stekeblad** [comment]
Update: I am currently working on the updater, more specifically how to make it secure and verifying digital signatures

**Comment by rcbalmera** [comment]
Thank you for the work you've . Pretty amazing. I currently used it. And I found it priceless.. Thanks man!!!

**Comment by Stekeblad** [comment]
I have now uploaded a new release (version 1.4.0) and submitted for verification. I have no idea how long it will take, but hopefully I've done everything right.

**Comment by seyfer** [comment]
@Stekeblad great job man, I hope it will work.

**Comment by Stekeblad** [comment]
I have received a confirmation that Stekeblads Video Uploader passed the verification!

Messages like "This app has not been verified yet by Google" and "Sign in with Google temporarily disabled" should not show up anymore.
