### ISSUE TITLE
tag not working...

### ISSUE THREAD

**Issue by cybergugu** [Stekeblad/Stekeblads-Video-Uploader#14]
$(rawname) tag not working... Just uploaded with name $(rawname)
If i didnt use presets, the software uses name automatically...
upd
in 1.3.3 tags are working fine

**Comment by Stekeblad** [comment]
Hi cybergugu and thank you for using my video uploader.
I have found the problem and I hope to have an update ready later this week.

**Comment by Stekeblad** [comment]
Hi again @cybergugu 
The update is now available on the releases page. You can also just open the 1.4.0 version of the program, it should find the update and ask if you want to update and do it automatically for you.
