### ISSUE TITLE
Stekeblads Video Uploader has reached its daily upload limit in the YouTube API...

### ISSUE THREAD

**Issue by nalegke** [Stekeblad/Stekeblads-Video-Uploader#17]
It was working fine for some time, but started to pop-up with 'upload limit' message on almost every single day now, even if there was no single upload processed in the last 2 days.

![Stekeblads](https://user-images.githubusercontent.com/2576800/85874552-27846200-b816-11ea-93b6-bbd4927b11ef.JPG)

The upload can still be done if closing that message and resetting the upload for several times manually.
Though, it won't add the video to the selected playlist on the YouTube's side and won't remove the pop-up message for the next upload.

**Comment by Stekeblad** [comment]
Hi @nalegke 
The type of error you see is something placed on Stekeblads Video Uploader by YouTube and this limit is shared by all users of Stekeblads Video Uploader.

Daily limit reached is an error code YouTube returns to the program. I can see in the statistics YouTube make available to me that the limit is never 100% reached and stops slightly below. I can do nothing about that happening before 100%.

I know the limit gets reached. I sent a request and was approved a higher quota limit only a few weeks ago, so I probably need to wait a few more weeks before I am allowed to request an even higher limit.

What you can do is double check that 18:00 is indeed equals to midnight pacific time in your time zone and try start uploading your videos shortly after that before other users feel up the limit.

**Comment by nalegke** [comment]
Hi @Stekeblad 
It looks better now and I haven't seen the daily upload limit pop-up in the last 5 days.
Not sure if the quota limit is raised on your end or SVU users are not uploading too many vids anymore.
As of suggestion, it would be nice to have the present counter of available uploads, so it can help to plan the amount of batch upload per day.
Speaking of sharing the same quota, is it possible to set up some sort of load balancing among the upload users / clients?
That would help to avoid the scenario of someone uploads 995 files out of 1000 daily max quota, while the rest of the users got only 5 upload slots left.

**Comment by Stekeblad** [comment]
I have not applied for another quota increase again yet, but will soon, and I can not say anything about if the usage has gone down the last few days as I've had problems the last week when trying to view the quota usage report from YouTube.

About your suggestion: I do not think I am allowed to check the amount of quota used with code, and I do not think it is a good idea to expose this information either.
I do not have the control to be able to properly implement a per-user limit. I could add it but would be easy to work around  because everything is on the user's computer. To do it properly I probably need to track users and uploads on my server, and I do not want to process any user information. The only time the program currently contacts my server is when checking for updates and no data is collected from that.

The solution is, instead of introducing a per-user limit, to apply for more quota when approaching the limit. However the new limit was reached so fast and I am worried that applying again to soon reduces my chances to get it increased. I will see if I can submit for more quota again next week if the quota usage report starts working.

**Comment by opranda** [comment]
Hi! Error [Screenshot](http://prntscr.com/tbgayo)

**Comment by opranda** [comment]
Can you add to the program that I can connect my Google APIs?

**Comment by Stekeblad** [comment]
Hi @opranda, I was about to move your comments to a separate issue but I found that the error you see when trying get video categories can appear not only if the codes are wrong but also if the quota limit makes the request fail, so your comment belongs here unless there is a space or other invisible characters in one of the input fields. It is on my to-do list for version 1.5 to improve the code and error handling related to the part interacting with YouTube.

When it comes to using your own API key: It is not, and will not, be supported.

**Comment by nalegke** [comment]
It might be hard to manage the max upload limit in the long term. YouTube has discontinued its classic uploader recently, so SVU is likely the best alternative at the moment.There should be more new users coming to upload multiple files on daily basis.
Today I've managed to upload only 4 simple files before getting the same error message:
"Stekeblads Video Uploader has reached its daily upload limit in the YouTube API..."

**Comment by Stekeblad** [comment]
> YouTube has discontinued its classic uploader recently
What classic uploader? The only official YouTube upload thing I know of is youtube.com/upload but they can not remove that.

> SVU is likely the best alternative at the moment.
Thank you very much!

Maybe I need to think again about adding a per-user limit, however it will not be added any time soon.

**Comment by nalegke** [comment]
The example of the classic uploader for multiple uploads:
https://www.youtube.com/watch?v=HEgJMKaUWN0
YouTube just removed that 'UPLOAD WITH CLASSIC' option completely.
It's funny to read the top comments about their new studio uploader :slightly_smiling_face:
https://www.youtube.com/watch?v=6C4dEpT0rYg

**Comment by Stekeblad** [comment]
Thank you @nalegke for the examples, this was the first time I saw the new studio uploading flow. I rarely upload videos myself, and the last few times I done it I used my uploader (of course).

Stekeblads Video Uploader has been granted an increased quota so now you can select your videos, apply your presets and hit the upload button!

**Comment by nalegke** [comment]
Thank you @Stekeblad, it looks working good now.
There is no 'daily upload limit' message coming up.

**Comment by nalegke** [comment]
Hi @Stekeblad, could you please check if the daily upload limit can be extended?
The daily limit message is coming up again. It allowed to upload just 1 video on yesterday and just 3 videos on today.

**Comment by Stekeblad** [comment]
Hi again @nalegke,
I noticed this issue earlier today and I have already submitted a quota extension request to Youtube, its now in their hands to review it.

**Comment by nalegke** [comment]
The expanded quota didn't last long on this time. Only one video upload before getting the 'daily upload limit' pop-up message.
Is the upload quota shared among all Stekeblads-Video-Uploader users or allocated individually based on IP/MAC addresses?

**Comment by Stekeblad** [comment]
The request has not yet been approved, I will update this issue when I have recieved the confirmation.

The daily quota limit is shared by all users with no limits on a per-user level. I am thinking about adding a notice in a comming update about not uploading too many videos in a single day and if that can have an effect.

**Comment by Stekeblad** [comment]
Additional quota has finally been approved, however Stekeblads Video Uploader was granted way less than I asked for (I got no explanation on why) so I can't mark this issue as solved. You will probably still be getting the quota limit reached error. I will try to find an explanation and then send a new request for additional quota.

**Comment by nalegke** [comment]
Thanks @Stekeblad, it looks better in the past couple of weeks. I've successfully processed about 25 uploads in one hour today without getting a "daily upload limit" message. The issue can be closed for now.
