### ISSUE TITLE
Show raw video title in bulk uploader

### ISSUE THREAD

**Issue by EgilSandfeld** [Stekeblad/Stekeblads-Video-Uploader#18]
Hey, thanks for making this. It's great.

One wish: Show the video file name somewhere on the main window. 
The reason: When uploading many files you cannot see which file you are editing.
I worked around it for now by adding $(rawname) to the Video title field, so I could distinguish them from each other.

**Comment by Stekeblad** [comment]
Hi EgilSandfeld and thank you for using Stekeblads Video Uploader!

I am currently working on a coming release and it will probably include some changes to how uploads and preset look like. I have written down your suggestion and will see if I find a good way to show the name of the video file.

What is your opinion? Do you think its a good idea if it was placed as the tool tip for the video name textbox or should it be directly visible without hovering/clicking on something? I am thinking a lot about the height of each upload/preset, what to show and that adding an extra row makes fewer elements in the list visible at a time.

**Comment by EgilSandfeld** [comment]
In my use case I was uploading 38 videos and quickly lost my orientation of
how far so scrolled. I would definitely need it to be present at all times
on the UI IMO

Best regards / Bedste hilsner
Egil Sandfeld

**Comment by Stekeblad** [comment]
To me it sounds like the best option in your situation is to, if possible, change how you name your video files and keep using $(rawname) as a part of the title.

Another solution could also be showing the file name in the initial status text when the upload is added until it's started or the status is changed by something else. I do not think the file name is important enough to most users to be visible all the time, but that is only a guess.
