### ISSUE TITLE
cannt open app

### ISSUE THREAD

**Issue by mp3096** [Stekeblad/Stekeblads-Video-Uploader#20]
i cannt open this java app for some reason debug shows 
C:\>java -jar Stekeblads_Video_Uploader-1.4.3.jar
Error: Could not find or load main class io.github.stekeblad.videouploader.main.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
how to fix it?

**Comment by Stekeblad** [comment]
What version of Java do you have? (run "java -version")

It looks like the graphics module JavaFX is not installed. JavaFX is included with Java 8 if you download it from java.com, other distributions of Java and newer versions from java.com does not include JavaFX.

Sadly I do not know any way to install JavaFX other than using the java.com Java 8 version that does not require you to manually install JavaFX by copying the files into your Java installation.

I know of this issue and are working on a solution that hopefully will be in the next big update, but its still much left to do on that update so it will not be out soon.

**Comment by mp3096** [comment]
I have installed Java 8 still it gives that error.
