### ISSUE TITLE
Start all ready uploads button not working after set preset and pick files

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [Stekeblad/Stekeblads-Video-Uploader#21]
I have done all settings but I can make it upload work. 
What happening?

Edit button not works after apply preset that why I saw that "upload not started"! How can I do?

**Comment by Stekeblad** [comment]
Hi @nguyenanhtuan1008, you do not give me much information to troubleshoot with. Can you please answer the following questions:

- Do you mean that both the edit button AND start all ready uploads buttons don't work for you or that you only have problem with the start all ready button?
- Do you get any popups with error messages? (And if so what do they say?) Some error messages can be copied and in this case its extra helpful if you paste the entire message compared to just a screenshot.
- Before clicking on "Start All Ready Uploads" check if the video details for your videos are in the editable state. If they are you must click the save button on all of them before you can start uploading.
- After clicking on "Start All Ready Uploads", do you see a progress bar on your videos and do any of the buttons on the videos change?

**Comment by nguyenanhtuan1008** [comment]
- "start all ready button" not working.
- NO show up any  "popups with error messages"
- Before clicking on "Start All Ready Uploads" check if the video details for your videos are in the editable state. If they are you must click the save button on all of them before you can start uploading. => I cannot click edit/save in those stages.
- After clicking on "Start All Ready Uploads", do you see a progress bar on your videos and do any of the buttons on the videos change? ->> no progress bar show up.

**Comment by Stekeblad** [comment]
I am not able to recreate your issue or find where it could happen
- Are you using the latest version of Stekeblads Video Uploader? If not then [download the latest version](https://github.com/Stekeblad/Stekeblads-Video-Uploader/releases) and try again.
- What is your operating system and version? What version of Java do you have? It can be some differences between operating systems and versions.
- If you apply the "-- NO SELECTED --" default preset, can you still not edit, save and upload or is it only if you select one of your own presets? Have you tried creating other presets and see if they work?

**Comment by Stekeblad** [comment]
Hi @nguyenanhtuan1008 

Do you still have problems or is it working now?
