### ISSUE TITLE
Cannot setup "localize category"

### ISSUE THREAD

**Issue by Mina-Tawfik** [Stekeblad/Stekeblads-Video-Uploader#22]
When I try "get categories":

- Login to youtube successfully
- Choose the channel
- Enter language code as "en"
- Enter the country code as "au"

I still get an error "The selected language or country code is not valid or not supported by YouTube, did not receive any categories"

![image](https://user-images.githubusercontent.com/39436871/113527521-2849f000-9601-11eb-9dff-c69dc56ec834.png)

Can anyone help with that?

**Comment by Stekeblad** [comment]
Hi @Mina-Tawfik 
There is currently a limitation in the error handling for retrieving categories and that error message is used for several different errors (its one of the things that will be improved in a coming update). The real error appears to be that Stekeblads Video Uploader is not assigned enough daily quota in the YouTube-API to serve all its users.

I have a pending request to YouTube for an increased quota that is waiting for them to review. You can follow the status about this in issue #17
