### ISSUE TITLE
ISSUES WITH HACKERS

### ISSUE THREAD

**Issue by LZAIYT** [Stekeblad/Stekeblads-Video-Uploader#23]
This software has been used by one of the user out there to post video such as cheat engine guide video on other youtubers video and make their channel got terminated.
Hope the creator by this software fix this so there's no one become the next victim with it

**Comment by LZAIYT** [comment]
![Screenshot_20210501-042458_Messenger](https://user-images.githubusercontent.com/83475504/116750733-7b169c00-aa35-11eb-81b4-ae786f248dc1.jpg)

My friend is one of the victims
and this is the message i send him when i realised he was been hacked

**Comment by LZAIYT** [comment]
![received_457207995539234](https://user-images.githubusercontent.com/83475504/116750818-a0a3a580-aa35-11eb-8aef-c68e606c0dd5.jpeg)

this is his screenshots that seems like the software got in his account by other hacker without notice

**Comment by QueenJames04** [comment]
Somehow I think someone used the software to bypass my accounts 2 factor and got into all of my emails than they uploaded a video to my channel and then just left my accounts alone for me to find it all.

**Comment by Stekeblad** [comment]
Hi @LZAIYT, I am sad to hear your friend got his account hacked.

For Stekeblads Video Uploader to be able to access a YouTube channel then someone with access to the channel owner's Google account must grant it permission to do so.

I tried using text recognition and translators to read the text in your last image and it turned into the following:
>(ale recent security activitiesc
) The
Google account
"Stekeblads Video Uploader" has been granted access to your Google account.
If you have not granted access, it means that someone else may be using your account.
Stekeblads Video Uploader has access to YouTube
industry activities from the following devices
Windows

That should mean that the hacker had access to the channel before they used this program to upload videos. From Stekeblads Video Uploader point of view its not possible to tell if the user is the real channel owner or a hacker, it only knows if it was granted access to a channel or not.

Hi @QueenJames04, Stekeblads Video Uploader does not request access to your emails, it only requests a few permissions around your YouTube channel and it should not be possible to trick Google to get full account access from the given permissions. They did not get access to your emails via Stekeblads Video Uploader.

**Both of you**, I recommend that you review your security settings and permissions for your Google accounts at https://myaccount.google.com/security and remove unknown third party programs, websites and devices that have access to your accounts. While there also look at recovery settings like secondary email and 2 factor recovery codes before changing your password.

This is probably a good place to also point out that the only official place to download Stekeblads Video Uploader is here on GitHub at https://github.com/Stekeblad/Stekeblads-Video-Uploader/releases and assume all other locations are fake and may contain malware or virus. After that you need to answer yourself if you want to trust the official downloads from me.

**Comment by Stekeblad** [comment]
I can not stop thinking about something in Stekeblads Video Uploader may be wrong and this issue is part of my decision to disable my API key for YouTube and require everyone to create one them self (can be done for free at console.cloud.google.com). In case the bad guys is only using Stekeblads Video Uploader as a tool to do their bad stuff a little easier this may only stop them for a short time but then its nothing more I can do.

This change will take effect around June 12-13 to give everyone that depends on the program to update.

I hope you manage to throw out the bad guys and get back full control over your accounts!
