### ISSUE TITLE
MKV video files not accepted

### ISSUE THREAD

**Issue by antoniu200** [Stekeblad/Stekeblads-Video-Uploader#25]
Hello!

When I try to upload any mkv video file, I get "One or more of the selected files was not added. It may have failed because only video files is allowed or they could not be read.
Invalid file type".

The "close" button displayed by that window does not do anything.

Dragging & dropping does not work.

Using Java 1.8.0_221.

**Comment by Stekeblad** [comment]
Hi @antoniu200 !

Stekeblads Video Uploader uses the built in file MIME checker in Java to verify that a selected file is a video. Drag-and-drop is currently not supported anywhere in the program. On the broken close button: I have found and fixed the issue.

Issue #4 was a similar issue (but for .webm) and it could be solved by changing the file extension, you can try that.

I have looked around a bit and found a better MIME checker that I want to try and if it works well it will be included in a future update.
