### ISSUE TITLE
SECURE YOUR SOFTWARE

### ISSUE THREAD

**Issue by codexecYT** [Stekeblad/Stekeblads-Video-Uploader#27]
This software is being spread rapidly for bad intentions!

People are hijacking content creators' accounts and then using this video to upload certain 'Spam-Like' videos such as "Free Fortnite Gift-Card" or "Fortnite ESP hack 2021" etc.

Please be aware that your software isn't being securely used at all.
Keep this in mind.

**Comment by Stekeblad** [comment]
Hi @codexecYT 
A similar question has been raised before, see #26 

Short summary:
- It is not possible to take over someone's account with only one of my releases of Stekeblads Video Uploader. Criminals need to get access to accounts/channels in other ways, like tricking you to enter the credentials in one of their malicious forms or tricking you to download and run their malware.
- Stekeblads Video Uploader is a powerful tool to make it easier to upload videos to YouTube. If normal user's find something very useful then its likely that criminals will think so to and there is little we can do about it.
