### ISSUE TITLE
Failed to upload the video 

### ISSUE THREAD

**Issue by aimbattt** [Stekeblad/Stekeblads-Video-Uploader#28]
Failed to upload the video "NAME VIDEO"
Here is the error details:
-----------------------------------------
400 Bad Request
POST was url
{
  "code": 400,
  "errors": [
    {
      "domain": "youtube.video",
      "location": "body.snippet.title",
      "locationType": "other",
      "message": "The request metadata specifies an invalid or empty video title.",
      "reason": "invalidTitle"
    }
  ],
  "message": "The request metadata specifies an invalid or empty video title."
}
-----------------------------------------
url 400 Bad Request
POST url
{
  "code": 400,
  "errors": [
    {
      "domain": "youtube.video",
      "location": "body.snippet.title",
      "locationType": "other",
      "message": "The request metadata specifies an invalid or empty video title.",
      "reason": "invalidTitle"
    }
  ],
  "message": "The request metadata specifies an invalid or empty video title."
}
	URLS
	at io.github.stekeblad.videouploader.youtube.Uploader.upload(Uploader.java:303)
	at io.github.stekeblad.videouploader.youtube.Uploader.access$000(Uploader.java:36)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:152)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:139)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stekeblad** [comment]
Hi @aimbattt , It looks like you tried to upload a video without giving it a name/title

**Comment by aimbattt** [comment]
> Привет @aimbattt , Похоже, вы пытались загрузить видео, не давая ему имя / заголовок

**Comment by aimbattt** [comment]
> Hi @aimbattt , It looks like you tried to upload a video without giving it a name/title

no, i give video name

**Comment by Stekeblad** [comment]
A few questions:
- Is this happening for all videos or only some of them?
- If its not happening on every video, can you see a pattern for when it works and when it fails?
- If you reset the failed upload, edit it and change the title (even just an extra space somewhere is enough). Can you then save that and try uploading again? Do you get the same result?

**Comment by aimbattt** [comment]
I found a solution to this problem, there was something with tags for the video, strange characters were less than 500 and everything was separated by commas. I removed the tags, leaving only one.

**Comment by aimbattt** [comment]
I found a solution to this problem, there was something with tags for the video, strange characters were less than 500 and everything was separated by commas. I removed the tags, leaving only one.

**Comment by Stekeblad** [comment]
So the tags made something with the title? Strange.

Anyway, good you found a solution. I am closing this issue.
