### ISSUE TITLE
After clicking "Get Categories" and "Yes", the following error appears ...

### ISSUE THREAD

**Issue by aimbattt** [Stekeblad/Stekeblads-Video-Uploader#29]
After clicking "Get Categories" and "Yes", the following error appears ...
https://imgur.com/NWKXH7g - error
https://imgur.com/gIPaaMV - settings

**Comment by Stekeblad** [comment]
Hi @aimbattt

There is currently a limitation in the error handling for retrieving categories and that error message is used for several different errors (it will be improved in a coming update). The real error is probably that the daily quota limit in the YouTube-API had been reached. I have sent a request for more quota and it is waiting for YouTube to review.
