### ISSUE TITLE
blank title when making preset

### ISSUE THREAD

**Issue by saiif2018** [Stekeblad/Stekeblads-Video-Uploader#3]
hi thanks for this amazing program 
i have isuue the videos i add when i add it to present it changes the titles into blank and i don't want to change the name of the file and when i don't use a preset it work great but the problem is i have to click  save on every video and i have to choose the category for every video it will take long time because i upload alot of videos  , can you fix this issue please and make the preset not changing the file name into blank :)

thanks

**Comment by Stekeblad** [comment]
I can easy add support for a [tag](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/$(ep)-and-$(playlist)) for use in the preset title that gets replaced by the original file's name.
Like if you enter "$(rawname)" somewhere in the preset title, $(rawname) will be replaced by the video file's name when you apply the preset.

I will add this and it will be in the next release (version 1.1.1)

**Comment by saiif2018** [comment]
is the next release  soon ?

**Comment by Stekeblad** [comment]
I will probably release version 1.1.1 shortly after Issue #4 is closed/solved
