### ISSUE TITLE
im trying to open the program but its not opening

### ISSUE THREAD

**Issue by TomerGamerTV** [Stekeblad/Stekeblads-Video-Uploader#31]
I have the latest java version installed and after trying to open it it's just doesn't open and if I try to do it from the terminal this is what it gives me

`D:\Downloads>java Stekeblads_Video_Uploader-1.4.5.jar
Error: Could not find or load main class Stekeblads_Video_Uploader-1.4.5.jar`

**Comment by Stekeblad** [comment]
Hi @TomerGamerTV

Try the following in the terminal `java -jar Stekeblads_Video_Uploader-1.4.5.jar` (note the extra -jar) Does it work do you get another error message?

What version of Java are you using? (`java -version`)

**Comment by TomerGamerTV** [comment]
> Hi @TomerGamerTV
> 
> Try the following in the terminal `java -jar Stekeblads_Video_Uploader-1.4.5.jar` (note the extra -jar) Does it work or do you get another error message?
> 
> What version of Java are you using? (`java -version`)

the command worked
the version is
```
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
```

**Comment by TomerGamerTV** [comment]
and can you add an option to upload videos as drafts? so I won't need to give them names?

**Comment by Stekeblad** [comment]
I take that as the original issue is solved.

If you upload multiple videos as drafts and without a name, how do tell them apart? Maybe you can upload your videos with the original filename as a title and set them as private? [Original filename can be inserted by presets](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/%24(ep)-and-%24(playlist)#rawname)

I do not know what benefits comes with the draft status and how it differs from the private status. If there is an important differens then I can look into if its possible to upload as a draft.

**Comment by TomerGamerTV** [comment]
> I take that as the original issue is solved.
> 
> If you upload multiple videos as drafts and without a name, how do tell them apart? Maybe you can upload your videos with the original filename as a title and set them as private? [Original filename can be inserted by presets](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/%24(ep)-and-%24(playlist)#rawname)
> 
> I do not know what benefits comes with the draft status and how it differs from the private status. If there is an important differens then I can look into if its possible to upload as a draft.

someone told me that I can back up my videos on YouTube and this is possible by keeping them private or as draft
and yes the issue is solved but I will have every time now run it from a command?

**Comment by TomerGamerTV** [comment]
![image](https://user-images.githubusercontent.com/44266242/129113647-4e95d29e-dc80-42d1-8c23-6cdd0f34a3ea.png)
I'm getting this error i can't upload, and I can't select or make any other category

**Comment by Stekeblad** [comment]
**The issue with categories**: Have you [dowloaded localized categories](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/Localize-Categories) from the presets --> localize categories window?

**It launches from the terminal but not with double-click**: I have some guesses on why it does not work. Do you have multiple versions of Java installed perhaps or that Java is not associated as the default program for .jar files?

It looks like you are on Windows and to avoid having to type the command every time you can try creating a file called "start-uploader.bat" in the same folder as the program .jar file, edit start-uploader.bat as a text file and enter the command in it. When you double-click the .bat the command will be executed and start the uploader. (if a terminal window only flashes open and then close you can add a second row to the .bat file with the word "pause" so you can see any error messages)
![image](https://user-images.githubusercontent.com/12627375/129139961-8700c90a-6e2c-4e10-af34-eaf0d4c45a8e.png)

**Comment by Stekeblad** [comment]
Stekeblads Video Uploader works best with Java 8. Later versions of Java no longer includes the graphics library JavaFX the program is built on by default. Including required component in the program is another thing I want to do. You can download JavaFX for later versions of Java but the last time I checked there was no easy way to install it and files had to be copied manually to different places.

You do not create a categories file manually. Look at the image below for where to find the Localize Categories window and the wiki page I linked above for a bit more info. After entering the required information in the window and you click Get Categories the program will get all categories YouTube allows you to use. In short: the language code can be for any language YouTube supports but the country code must be for your country or your videos may end up in the wrong category or fail to upload.
![image](https://user-images.githubusercontent.com/12627375/129227222-18c4fccb-c7f8-4a97-ab40-03a1e9c85c48.png)

**Comment by TomerGamerTV** [comment]
Okay I will check it I didn't see it last time

**Comment by TomerGamerTV** [comment]
it worked but I got this error


Sorry, something went wrong!
Here is the error details:
-----------------------------------------
null
-----------------------------------------
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at io.github.stekeblad.videouploader.main.mainWindowController.onUploadErred(mainWindowController.java:897)
	at io.github.stekeblad.videouploader.main.mainWindowController.lambda$null$4(mainWindowController.java:150)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stekeblad** [comment]
Hi

That error comes from a piece of code triggered when an upload fails because Stekeblads Video Uploader has reached its daily limit against YouTube as well as because of really bad timing between two things. I think I know how to solve it but until an update is available you can retry your uploads and its unlikely you will see that specific error again.

**Comment by Stekeblad** [comment]
Closing this issue, your last error can be tracked in issue #34
