### ISSUE TITLE
can't login in account

### ISSUE THREAD

**Issue by Vampire1991** [Stekeblad/Stekeblads-Video-Uploader#33]
![image](https://user-images.githubusercontent.com/30973355/129425302-a8c1c6e6-a27e-428f-aa43-ae2856e46441.png)
after clicking"yes" nothing happens,my def browser is chrome

**Comment by Stekeblad** [comment]
Hi @Vampire1991 
Do you mind sharing your solution for others that may run into the same issue?

**Comment by Vampire1991** [comment]
I just deleted folder videouploader data,but you can just delete folder .auth
