### ISSUE TITLE
I Am Facing New Issue When I am Going To Upload Videos Showing Error

### ISSUE THREAD

**Issue by Amitsarkar009** [Stekeblad/Stekeblads-Video-Uploader#34]
![error11](https://user-images.githubusercontent.com/89314818/130330112-3a23f589-fe79-4c74-8548-63e5ff4d8e8b.png)
![Error](https://user-images.githubusercontent.com/89314818/130330115-83c29a9c-427e-4a51-8ade-2a558534b028.png)

Check The Photos And Give Me Solution

**Comment by Stekeblad** [comment]
Hi @Amitsarkar009 

Let's start with the last image about the daily upload limit. All programs that interact with YouTube using their APIs have a limit assigned to them that gets reset every day. Stekeblads Video Uploader was assigned a higher limit last week but I have seen it's not enough to meet the demand and I am in contact with Google to increase the limit further. I can not promise when the limit will be increased, it is currently in the hands of Google.

The error in the first two images was recently posted in another issue. I have diagnosed that this error can sometimes occur when the daily limit gets reached. I think I know the source of it and a fix will be included in the next update.

I recommend you retry your uploads again at about 14:00 or later in your local time, if possible. It's sad but you currently have to fight for the available quota with the other users.

**Comment by Stekeblad** [comment]
Hi @Amitsarkar009 
This should be fixed in version 1.4.6 that I released a few hours ago. You should be notified about the update next time you open Stekeblads Video Uploader. If you have disabled automatic update checks you can manually check for updates from the settings window.
