### ISSUE TITLE
i wanted to notify you about a issue regarding people misusing your software

### ISSUE THREAD

**Issue by yazdispazdi** [Stekeblad/Stekeblads-Video-Uploader#35]
your software has been misused by hackers/scammers who mass upload valorant hacking videos, and in the description of those videos it includes a download link to a hacking client, a hacking client that is used to get more victims in order to upload more viruses, this is a violation of the Privacy Policy for Stekeblads Video Uploader. Hope you can do something about this.

**Comment by Stekeblad** [comment]
Hi @yazdispazdi 

Uploading that kind of content does not only violate the terms of Stekeblads Video Uploader, it violate YouTubes terms as well. I am aware that hackers/scammers use Stekeblads Video Uploader as a part of their criminal activities but I do not know if/what I can do about it when not even Google recognise their videos as a scam.

If you, or anyone else out there, can think of something that could be implemented and that does not cause more problems for the good users than the bad once then please suggest it here so we can discuss it.

**Comment by sukrosono** [comment]
OMA, @yazdispazdi which video do you think is using this software, and are hackers/scammers? 
if you could provide the URL, we can examine it.
Well by your information they do not deserve to be called a hacker.
Some hacking tutorials are still available on youtube and for a good reason.

As @Stekeblad , Well I think it's not worth our time. Youtube will soon ban/delete those kinds of videos.
They do use human review on reports, so AFAIK if that kind of videos is really scam/spam it will be terminated in one or two years.
