### ISSUE TITLE
I Facing Problem From Many Days

### ISSUE THREAD

**Issue by Amitsarkar009** [Stekeblad/Stekeblads-Video-Uploader#38]
I[](url)
![ddddddddddddddddddddddd](https://user-images.githubusercontent.com/89314818/132099401-1a61058f-4ba7-4706-a039-52687b82c741.png)
I am Facing This Problem From Many days . when i am changing account same problem showing.
my all conceted stekeblads account showing this problem. if any solution plese tell me

**Comment by Stekeblad** [comment]
Hi @Amitsarkar009 

That error is something between me and YouTube. The popularity of Stekeblads Video Uploader is growing faster than I can handle. That daily limit is shared between all users and YouTube have already granted me a higher limit two times during the last month. I will begin the process of increasing the limit further but it will take some time for it to be approved. In the mean time you have to fight the other users over the available quota.

**Comment by sukrosono** [comment]
Well, I appreciate this software, I just think a better (IMO) UI message.
Just as the current warning but have additional text like so:
```
If you are just a daily / weekly uploader and in a rush.
You can use the youtube studio web interface to upload one or two videos.
Just make sure which video is not done yet, also reconsider your upload priority.
```

I don't have any intention to offend the owner, this is already great work.
I might try next month.
Side note, you can implement this if the upload job abortions are really high. Which confirmed by stekeblads user on github issue.
Cheers :smile:

**Comment by Stekeblad** [comment]
Hi @sukrosono 

That is a good suggestion. I will think about what wording to use and add a updated message in the next update.

**Comment by Dubrovsly** [comment]
please tell me what to do with such an error
![2022-03-31_00-17-04](https://user-images.githubusercontent.com/102687928/160893600-476f3c26-fc1c-46d8-84db-a70df5e17a43.png)
