### ISSUE TITLE
Hackers using the software ill intently.

### ISSUE THREAD

**Issue by iWannaSmashMyKeyboardSoBadly** [Stekeblad/Stekeblads-Video-Uploader#39]
is there anyway you can make an uninstaller?, as hackers are using your software ill intently to upload videos like "Free genshin impact hack" and "free csgo cheat". an uninstaller would help alot for people who have been infected.

**Comment by KazumaSakai420** [comment]
Same thing happened to me and my brother last night. How is it possible that random people can use this to upload to others ppl channels. Creator of this should really look into this

**Comment by Stekeblad** [comment]
Hi @iWannaSmashMyKeyboardSoBadly I do not believe an uninstaller would help as I think the hackers are most likely is not uploading from your computer. The closest to "uninstalling" currently is to click on the "clear stored data" button in the settings window and then "log out and delete", closing the program and lastly deleting the files.

**Comment by Stekeblad** [comment]
Hi @KazumaSakai420 Stekeblads Video Uploader can not be used to upload videos to any channel. To be able to upload to a channel the user must be able to prove one of the following things to Google:

That the user
- is logged into the account owning the channel
- can log in to the account owning the channel
- or (unsure) if they can do one of the above for an account that [has been granted permission to manage that channel](https://support.google.com/youtube/answer/9481328?hl=en)

I have made investigations into this and all results points to that the hackers first use one of countless tactics to gain access to someones account and then first after succeeding use Stekeblads Video Uploader to upload videos. From the perspective of Stekeblads Video Uploader then nothing is wrong:
- The program tells the user that they need to log in to perform a certain action (for example start an upload).
- The user confirms and is directed to Google
- The program receives a token from Google that allows it to interact with the channel it was created for.
- If Google does not receive that token later together with a request (or the token is invalid) they will return an error message.

**Comment by Stekeblad** [comment]
I have shared the following links before in other issue and I add them here as well:

[support.google.com - Secure a hacked or compromised Google Account](https://support.google.com/accounts/answer/6294825)

[myaccount.google.com/security](https://myaccount.google.com/security)

**Comment by KazumaSakai420** [comment]
I already changed everything. Its really sad that people misuse useful
stuff like your programm

Stekeblad ***@***.***> schrieb am Do., 9. Sep. 2021, 18:13:

**Comment by frosDfurret** [comment]
I too am a victim. I'd recommend resetting your password AND setting up 2FA on your Google accounts affected, which is something I'm surprised I didn't already do.
Also consider using Avira or a similar software to do a virus scan, just in case.
If all goes south, factory resetting the PC listed in the "Account Activity" page on Google can be a last resort, which is what I will likely be doing sometime soon.

**Comment by shadowmanisme** [comment]
HOW TO FIX IT? I AM HACKED TOO;(

**Comment by Stekeblad** [comment]
@shadowmanisme Please look at the links I posted in a comment above.
