### ISSUE TITLE
.webm files are not recognized as videos

### ISSUE THREAD

**Issue by saiif2018** [Stekeblad/Stekeblads-Video-Uploader#4]
i Noticed that the program does not recognize some video extentions like .webm witch is can be uploaded to youtube :)

**Comment by Stekeblad** [comment]
The program checks the content type (MIME) of files, not the extension. If the content type of a file you want to upload starts with "video/" it will be accepted. According to [webm project](https://www.webmproject.org/docs/container/) webm videos should have the MIME-type "video/webm".

In other words, webm should work. Do other types of video files work? Can you check the content type of one of the files that you could not add?

**Comment by saiif2018** [comment]
sorry man i meant .webm files .

**Comment by Stekeblad** [comment]
I am talking about .webm video files

**Comment by saiif2018** [comment]
did you try choosing .webm file , i tried diffrent extentions and it worked but .webm dosent work when i pick the file it does not show in the box

**Comment by saiif2018** [comment]
its no big issue but i just wanted to notify you about it , because i can just change extention of the videos and it will work fine

**Comment by Stekeblad** [comment]
I have now tried with a .webm video file and it detects the content type as "null". (It does not know what it is.)
I cant find much information on this, the only solution that would make .webm videos to work I can see right now is to add a specific test for the .webm extension but I dont like that solution.

I was about to suggest you migrate to another file format but if it works by just renaming the files, do that!
