### ISSUE TITLE
Do something about this application or remove it

### ISSUE THREAD

**Issue by DiaryOfAstra** [Stekeblad/Stekeblads-Video-Uploader#40]
Tons of channels including mine are being hacked into using your very own program, It's useless, I can upload a video myself without this. Kindly notice that you might say it's not my fault but it's YOUR program, You're responsible for it's consequences and you MUST stop this crap. Channels are getting banned because of this, My accounts are hacked and given permission to your app, How? I don't know. 
The device is logged in from Russia
DO SOMETHING ABOUT THIS, IF YOU GOOGLE YOUR APP'S NAME YOU WON'T SEE ANYTHING BUT HIJACKERS AND SUSPENSIONS.

**Comment by Stekeblad** [comment]
Hi @DiaryOfAstra 

I am aware that bad guys are using this program. If you look at the other issues here you can see this has been disscussed several times. I will not repeate the same answers I already given in those issues here. Please look at them.

For your "new" question: "I can upload a video myself without this."

Yes, you can. If you are only uploading a video once in a while you may not have any problems with uploading using YouTubes upload page. But if you on the other hand upload several videos per week or daily you will soon find you spend a lot of time setting video properties on the upload page. Stekeblads Video Uploader was created so users can spend less time setting video properties so they instead can start working on their next video.

**Comment by yasmeen2001234** [comment]
> Tons of channels including mine are being hacked into using your very own program, It's useless, I can upload a video myself without this. Kindly notice that you might say it's not my fault but it's YOUR program, You're responsible for it's consequences and you MUST stop this crap. Channels are getting banned because of this, My accounts are hacked and given permission to your app, How? I don't know. The device is logged in from Russia DO SOMETHING ABOUT THIS, IF YOU GOOGLE YOUR APP'S NAME YOU WON'T SEE ANYTHING BUT HIJACKERS AND SUSPENSIONS.

You are absolutely right my friend , I recently got my YouTube channel banned due to the program (  granted stekeblads access ).  I am extremely upset and hope karma happens to the hacker and the creator of this useless program ( if he did not fix it ) .

**Comment by NikosLaw** [comment]
> Hi @DiaryOfAstra
> 
> I am aware that bad guys are using this program. If you look at the other issues here you can see this has been disscussed several times. I will not repeate the same answers I already given in those issues here. Please look at them.
> 
> For your "new" question: "I can upload a video myself without this."
> 
> Yes, you can. If you are only uploading a video once in a while you may not have any problems with uploading using YouTubes upload page. But if you on the other hand upload several videos per week or daily you will soon find you spend a lot of time setting video properties on the upload page. Stekeblads Video Uploader was created so users can spend less time setting video properties so they instead can start working on their next video.

                                                                                     Fuck you
