### ISSUE TITLE
program abuse

### ISSUE THREAD

**Issue by NotRandomPerson** [Stekeblad/Stekeblads-Video-Uploader#41]
all I need to know is if there is any file location or where I can find the program that has infected my google account.

**Comment by Stekeblad** [comment]
Hi @NotRandomPerson 
First, to be clear, Stekeblads video Uploader is a legitimate program that some bad guys found useful and use _after_ they gained access to someones account.

Malware can come from almost anywhere, E-mail attachments, random files found on the internet or evil websites. Some types does not stay on your computer and take what they want and leave. If they stay they can hide anywhere, I recently read about a type of malware hiding inside the GPU.

If you are looking for where Stekeblads Video Uploader may be on your computer then I can't help you, There is no default directory or similar. Stekeblads Video Uploader and its settings files are created in the directory its executed. Further, after gaining access to your account the bad guys are likely to continue from some other computer and not from yours.

I am sorry but I can't do much to help you

**Comment by oliverosM** [comment]
question, if I change the password of my account they o whoever they are will stop having access?? Thank you.

**Comment by Stekeblad** [comment]
Hi @oliverosM 

I can't answer that question. You should definitely change your password but if you want to properly secure your account you need to do more. Here are two good Google pages to help you:

https://support.google.com/accounts/answer/6294825
https://myaccount.google.com/security
