### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by decoder0007** [Stekeblad/Stekeblads-Video-Uploader#42]
Someone logged into my google account without my authorization and started uploading GTA V hacks to my account. I got an email saying Stekeblads Video Uploader was granted access to my account. Attached below is the image of the email.
![image](https://user-images.githubusercontent.com/50407945/135471883-c6d1513d-f76c-4257-850e-f91f5b13f2ab.png)

**Comment by Stekeblad** [comment]
Hi @decoder0007 

There are already multiple similar issue, both open and closed, please look at them. If you still have questions after that you can comment here with a more specific question.
