### ISSUE TITLE
Easy for hackers to use

### ISSUE THREAD

**Issue by Ahmedeldeeb91** [Stekeblad/Stekeblads-Video-Uploader#43]
I received notification that uploader granted access without even knowing what the fuck is stekeblad !!!
And my channel deleted after youtube found that uploaded video violates terms and guidelines
Stop this bullshit app asap

**Comment by Stekeblad** [comment]
Hi @Ahmedeldeeb91 

I am sorry to hear you lost your channel

Stekeblads Video Uploader was made to make it easier to upload videos. It helps many users, but sadly some of them use it for uploading to hacked accounts.

However. Stekeblads Video Uploader is not a tool for hacking channels. It can only access a channel if the user can prove to Google they have permission to the channel and should be allowed to grant other programs access to it. From the perspective of the program it is impossible to tell a legitimate user apart from someone using a hacked account.

**Comment by teriaq01** [comment]
same thing happened to me, seems like this Stekeblad is causing more trouble than help, they should delete Stekeblad before more people get there account deleted forever
