### ISSUE TITLE
Stekeblads Video Uploader was granted access to you google account !!!!

### ISSUE THREAD

**Issue by yasmeen2001234** [Stekeblad/Stekeblads-Video-Uploader#44]
Can you the creator of the program plz explain how I got hacked and granted access to this FU*** program ??? 

My google account is highly secure with 2-step verification , and when I got the email I removed the access and changed 
my password but still they were able to upload videos on my channel. Videos that were illegal or against YouTube guidelines , which lead to banning my YouTube channel.   

I am heartbroken and confused at the same time , I read other people issues and your respond was like ( " Stekeblads Video Uploader was made to make it easier to upload videos " ) ( "Stekeblads Video Uploader is not a tool for hacking channels " ) 

I know you work hard on the application , the coding and the debugging etc. , but no normal person uses stekeblads to upload videos.  I means it is kinda useless , only hackers could really benefit from it. Plz do something about it or ....

**Comment by WolfTM** [comment]
Well let me go in on this topic.

How would you explain all of my google accounts were granted your stuff permission to youtube at the same time.
![Screenshot_115](https://user-images.githubusercontent.com/73074029/146640472-40a8a2ef-6b74-4616-b0d0-2b814391b2d8.png)
From my own device?
Without me knowing? You got some shady stuff going on here.

I would like a valid reason why this is happening without my supervision. All at the same time and even from my own device.
I think your stuff is implemented in software and other stuff. Software that uses a mask to cover the truth of them selfs.

This happened after I installed an app called DriverMax to update my drivers.
Very shady. If no valid reason you and DriverMax will be under fire.
This will be reported to Google and others.

**Comment by Stekeblad** [comment]
Hi @WolfTM 

I have never heard of DriverMax but when I look it up I find just what you mention, [Malwarebytes flags it as a potentially unwanted program](https://blog.malwarebytes.com/detections/pup-optional-drivermax/). I also saw links to "cracked" versions and unofficial downloads, these have a high risk of including malware with the installation. Always download stuff from the official location to reduce the risk of getting other unwanted stuff at the same time...

If it happened to all your accounts at the same time then it sounds like some malware may be on your computer and has stolen all your cookies and saved accounts from your browsers. With this it can pretend to be you, Google and others will believed it.

I am not sure what more to say other than that you should hurry checking and securing your accounts. It's likely more than just your Google accounts that are at risk. I hope you can get those bad videos deleted and you do not get more unpleasant surprises.

**Comment by WolfTM** [comment]
Yes,

I get it I payed for the software but that is not the point. If you are unaware than others are abusing your software currently.
And are using it for illegal purpose. I find it sad that this happens but at the same time I am glad that it is not you.

Sorry for the words. I will report this and the software and get it checked out.
MY PC is clean now. I just find it so sad why people have to use other people their creations and abuse them.
Sorry for this. Keep up the great work on your app.
