### ISSUE TITLE
please can you private this app or github thing

### ISSUE THREAD

**Issue by theloser7455** [Stekeblad/Stekeblads-Video-Uploader#46]
like for real someone hacked my youtube account (thegodloser) and i got banned forever becuase
the hacker hacked my microsoft/windows 10 account with a remote thing
so please private ur app or github or idk

**Comment by thedavesorh** [comment]
or just make a new update of the app that needs a google password or something

**Comment by thedavesorh** [comment]
it's not a malwere.
