### ISSUE TITLE
upload is limited to 100 per day 

### ISSUE THREAD

**Issue by saiif2018** [Stekeblad/Stekeblads-Video-Uploader#5]
hi thanks for the $rawname   , but i noticed that the upload is limited to 100 per day i don't know whats the problem its limited to 100 videos per day like when you upload from the browser . it should be at least 400 videos limit .

**Comment by Stekeblad** [comment]
Someone is uploading a lot!  :)

"Like when you upload from the browser" - That sounds like a limit set per account on YouTube's side. I can see that my the limit on my program has not been reached yet and I tried successfully uploading a test video.

**Comment by saiif2018** [comment]
but they say i am allowed to upload up to 400 videos

**Comment by Stekeblad** [comment]
If the problem also happens then you try to upload from the browser then it is something on YouTube and I can not do anything about it, sorry.
