### ISSUE TITLE
Failed Google when im connect account 

### ISSUE THREAD

**Issue by doezepos** [Stekeblad/Stekeblads-Video-Uploader#50]
## Authorization Error

**Error 403: rate_limit_exceeded**

Currently, this app has reached the maximum allowable login request rate.

Google limits the speed at which apps can allow new users to sign in. You have the option to try logging in again later, or ask the developer ([EMAIL-REMOVED]) to increase the maximum allowable sign-in rate in this app.

If you are the developer of this application, you have the option to request an increase in the maximum allowable rate for creating login requests.

---

How i can fix this error?

**Comment by Stekeblad** [comment]
Hi @doezepos 

That does not like an error you can do anything about, it is something I need to look into.

You could wait a few hours or until tomorrow before retrying and hope that the rate limit has updated to allow new attempts again.

**Comment by doezepos** [comment]
Thanks for the quick response! I will wait

**Comment by doezepos** [comment]
![image](https://user-images.githubusercontent.com/93837058/140623438-db017086-81c9-45b9-88ab-437b08bac95f.png)
btw, forgot about that, maybe this will help in some way
(text)
If you’re the app developer, make sure that these request details comply with Google policies.

    response_type: code
    redirect_uri: http://localhost:52363/Callback
    client_id: 357246313308-ghki8t5aq9c8uq8a5nar2dhpvmu5i43e.apps.googleusercontent.com
    access_type: offline
    scope: https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube
