### ISSUE TITLE
Feature Request: Scheduling when videos get published

### ISSUE THREAD

**Issue by cybergugu** [Stekeblad/Stekeblads-Video-Uploader#51]
Hello,
I sthere a posibility to add feature like video publishing at certain time? I think there is api command that could do this.

**Comment by Stekeblad** [comment]
Hi @cybergugu 
That is actually something I have been thinking about!

It is on my list of things I would like to try adding, but I'm not sure how I want it to work for users configuring it. (Will it work with presets too, like publish the videos with a certain intervall? How would the UI for that be like?)

I have a few other changes that needs to be done first and then I need to figure out the things above so it will not happen any time soon.

**Comment by cybergugu** [comment]
Hello,
is there any progress regard this feature?

**Comment by Stekeblad** [comment]
Hi @cybergugu 

Stekeblad's Video Uploader is currently on ice while I am working on some other side projects. I will come back to this project and feature later but can't say anything about when.
