### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lemonsflo** [Stekeblad/Stekeblads-Video-Uploader#52]
An error started popping up on my account during authorization ((
![hgffghgf](https://user-images.githubusercontent.com/94681971/142603248-1a8df5ad-be1a-4809-9581-a2830a106aba.JPG)
(

**Comment by Stekeblad** [comment]
Hi @Lemonsflo I suggest that you do what the message says and check the security settings section for your account at https://myaccount.google.com/security and follow the Google Account Security Checkup

**Comment by Egorchiku** [comment]
![Screenshot_503](https://user-images.githubusercontent.com/100325943/155438429-7f4bc51e-762c-4130-a7d2-c3ff25b6a83f.png)

**Comment by Stekeblad** [comment]
Hi @Egorchiku 

The codes lock correct, assuming there is no invisible characters like spaces hiding.

That error message can also appear when the daily qouta limit for Stekeblad's Video Uploader has been reached, se #22

**Comment by Egorchiku** [comment]
How i can contact you?

**Comment by Stekeblad** [comment]
I prefer to handle it here as an GitHub issue if possible, if not you can send an email tp uploader@ ste .ke
