### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by doezepos** [Stekeblad/Stekeblads-Video-Uploader#53]
![image](https://user-images.githubusercontent.com/93837058/142769457-7661b61d-9707-4f43-8d7a-27b4496fc1f4.png)

**How do you get around it?**

**Comment by Stekeblad** [comment]
Hi @doezepos [That is a standard Google security feature](https://support.google.com/accounts/answer/7162782?hl=en&co=GENIE.Platform%3DAndroid)

It looks like Google wants to verify its really you by requesting you to enter a code on your phone. I assume you own a LG K4 and a (Samsung) Galaxy A51, they should have received a push notification. Follow the instructions in the message.

**Comment by Lemonsflo** [comment]
I've written about this before( I have five channels. I bought three of them... I can't log in to them( Because there is no access to these phones( It's a pity, you had a good program (

**Comment by Stekeblad** [comment]
@Lemonsflo I'm sorry but I can't help if you have problem accessing your Google account(s).

If you made a legitimate purchase from the real owner of a channel then I guess it's probably pretty easy to contact them for help with changing linked devices and other settings.
