### ISSUE TITLE
File not opening?

### ISSUE THREAD

**Issue by martins9009** [Stekeblad/Stekeblads-Video-Uploader#55]
When launching the program nothing happens? I have java installed

**Comment by Stekeblad** [comment]
Hi @martins9009 

- What is your operating system and version?
- What version of Java do you have installed?

You may get som more details about the error if you try to open the program from the command line, the command looks like this:
`java -jar Stekeblads_Video_Uploader-1.4.3.jar`

**Comment by martins9009** [comment]
Hey! Windows 10 pro. The newest one from their website. After opening in cmd prompt it says unable to access jarfile Stekeblads_Video_Uploader-1.4.3.jar

**Comment by martins9009** [comment]
Okay I got it to work on cmd heres what it says:
Error: Could not find or load main class io.github.stekeblad.videouploader.main.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by Stekeblad** [comment]
That was what I expected, see also this issue: https://github.com/Stekeblad/Stekeblads-Video-Uploader/issues/20

Your options are:
- Downgrade to Java 8
- Figure out if/how to add JavaFX for your version of Java

I have made attempts upgrading to use newer versions of Java but I run into problems I have not been able to solve.

**Comment by martins9009** [comment]
Uninstalling all java programs at Software and Features on windows 10 and then reinstalling just java 8 seemed to work.
