### ISSUE TITLE
Heloo sir please grant my youtube account and upload some video

### ISSUE THREAD

**Issue by Jackbhai511** [Stekeblad/Stekeblads-Video-Uploader#57]
Reply me

**Comment by Jackbhai511** [comment]
Please grant my youtube account and upload videos

**Comment by Stekeblad** [comment]
Hi @Jackbhai511

If you can't find the download page then it is here: https://github.com/Stekeblad/Stekeblads-Video-Uploader/releases

If you don't know how to use the program I hope you can find the help you need in the wiki: https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki

If that does not answer your question, please provide more details of what you want to do.
