### ISSUE TITLE
YOUTUBE ACCOUNT HIJACK

### ISSUE THREAD

**Issue by crypt1clol** [Stekeblad/Stekeblads-Video-Uploader#58]
hi my youtube got hijacked and random videos are being uploaded by stekeblads

**Comment by Stekeblad** [comment]
Hi @crypt1clol 
I am closing this as a duplicate, please see [Stekeblads Video Uploader was granted access to you google account](https://github.com/Stekeblad/Stekeblads-Video-Uploader/issues/44)
