### ISSUE TITLE
dont eat my vids(

### ISSUE THREAD

**Issue by kiop12548** [Stekeblad/Stekeblads-Video-Uploader#60]
I try with mp4 and mp3, and i have this error- "One or more of the selected files was not added. It may have failed because only video files is allowed or they could not be read. 123.mp4 - Invalid file type"

**Comment by Stekeblad** [comment]
Hi @kiop12548 

There is a known issue with some video formats not being allowed ( issues #25 and #4 ) but mp4 should work, that is the format of my test files. When it comes to mp3 however, that is a format for audio files and that is not allowed.
