### ISSUE TITLE
Uploading public videos from an API client?

### ISSUE THREAD

**Issue by impressiveaustin** [Stekeblad/Stekeblads-Video-Uploader#62]
How did you get YT API key that allows you to publicly upload videos? When I get my API key, it won't allow me to upload public videos. It auto privates them.

**Comment by Stekeblad** [comment]
Hi @impressiveaustin 

To be able to publish videos with visibility status public from an API client you must request YouTube to perform an audit on your project. See the documentation for videos.insert: https://developers.google.com/youtube/v3/docs/videos/insert

**Comment by impressiveaustin** [comment]
Can I pay you to create me an API client and secret that has the audit thingy? Like a "premium" version of this or a "private" version?

**Comment by Stekeblad** [comment]
No, I'm sorry.

I will not create an API client for you, you have to set it up yourself and submit the audit form

**Comment by impressiveaustin** [comment]
How come sometimes uploading works sometimes it gives error on wait till 12AM even though if I keep spamming to retry it works like 3 times then does error message again?

**Comment by Stekeblad** [comment]
Do you mean the daily limit reached error?

Do you mean that you ignore the error and just try again and again? If so and that sometimes works then that is something on YouTube how they track usage. Maybe it has something to do with keeping all their servers around the world in sync so they block some requests when approaching the limit to not allow the program to use more than it is allowed to?
