### ISSUE TITLE
use proxy

### ISSUE THREAD

**Issue by susantha1995** [Stekeblad/Stekeblads-Video-Uploader#66]
hi, do I need to use proxies when uploading bulk videos to youtube? or upload bulk videos on two youtube account the same day? if yes is there any way to add proxies to GUI?  or can we use this to upload videos to multiple accounts same day with the same local IP?

**Comment by Stekeblad** [comment]
Hi @susantha1995 

Stekeblads Video Uploader does not have built in support for multiple channels, but that is easy to work around by having multiple copies of the program in different directories. There is nothing in Stekeblads Video Uploader preventing you from uploading to multiple channels on a single day.

**Comment by susantha1995** [comment]
ok thank you for your reply and I got your point. but I'm asking about the youtube side, in your experience, will youtube ban/limit my accounts if I upload bulk videos to multiple channels on the same IP address?

**Comment by Stekeblad** [comment]
I can't answer for how YouTube's algorithms work. I only have one channel and I am currently not actively uploading to it so I have no experience with being blocked for uploading too much.

Sorry I can't give any better answers.
