### ISSUE TITLE
feature request: use title metadata

### ISSUE THREAD

**Issue by jongkok** [Stekeblad/Stekeblads-Video-Uploader#7]
Thank you for such amazing tool !
Perhaps you could add feature that allow us to use file's metadata (eg. Title) as uploaded video title ?
Thanks

**Comment by Stekeblad** [comment]
Adding support for reading metadata is actually on my "maybe sometime in the future"-list. I will look closer to see how difficult it is and update here later this week about what I find.

If you can give the video files the same name as in the title metadata you can use the [$(rawname) tag](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/%24(ep)-and-%24(playlist)#rawname) as an alternative solution

**Comment by Stekeblad** [comment]
I have found a library for easy extracting of metadata for some video formats. I have started working on implementing it as a tag. Current idea is for it to work like below but it may change.
`$(metadata:title)`
or maybe also fallback support if a specific tag is not found in a file
`$(metadata:year,2019)`

**Comment by jongkok** [comment]
Thank you...sounds promising. Looking forward to test it when available.
Now I'm not sure what to do with this issue....should I close it or leave it open ?

**Comment by Stekeblad** [comment]
Wait with closing the issue.

I want to have it open atleast untill the feature is done, I will not close it directly afterwards so you have a chance to give feedback.

I have found that I only have a couple of files I can use for testing so your feedback when its done will be very helpful.

**Comment by Stekeblad** [comment]
[You can now get version 1.3 from the releses page!](https://github.com/Stekeblad/Stekeblads-Video-Uploader/releases) It contains the new meta data-tag. It works like described above and for more information the wiki is already updated, you can look at the [tags page](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/%24(ep)-and-%24(playlist)) and the new [Meta Data Tool Window page](https://github.com/Stekeblad/Stekeblads-Video-Uploader/wiki/Meta-Data-Tool-Window)

**Comment by Shivchik** [comment]
Hi! Thanks for the soft! Is it possible to use a video file name in a title?
